CREATE TABLE [dbo].[TmpRecipient] (
    [RecipientID]                        BIGINT         NOT NULL,
    [RecipientName]                      VARCHAR (50)   NULL,
    [RecipientAddress]                   VARCHAR (100)  NULL,
    [RecipientAddress1]                  VARCHAR (100)  NULL,
    [RecipientCity]                      VARCHAR (50)   NULL,
    [RecipientState]                     VARCHAR (50)   NULL,
    [RecipientZip]                       VARCHAR (30)   NULL,
    [RecipientCountry]                   VARCHAR (50)   NULL,
    [CurrencyType]                       VARCHAR (10)   NULL,
    [TransactionType]                    VARCHAR (10)   NULL,
    [AccountType]                        VARCHAR (10)   NULL,
    [FinInstCountry]                     VARCHAR (2)    NULL,
    [RecipientEmailAddress]              VARCHAR (50)   NULL,
    [EmailAddress2]                      VARCHAR (50)   NULL,
    [EmailAddress3]                      VARCHAR (50)   NULL,
    [EmailAddress4]                      VARCHAR (50)   NULL,
    [RecipientStatus]                    TINYINT        NOT NULL,
    [CreatedBy]                          INT            NULL,
    [CreatedDate]                        DATETIME       NOT NULL,
    [ParentRecipientID]                  BIGINT         NULL,
    [LastLogRecipientID]                 BIGINT         NULL,
    [RecipientAddedType]                 TINYINT        NULL,
    [UsePayeeNameFromFile]               BIT            NOT NULL,
    [ApprovedCount]                      TINYINT        NOT NULL,
    [IsAllApproved]                      TINYINT        NOT NULL,
    [TransitCode]                        VARCHAR (255)  NULL,
    [RecipientAccountNo]                 VARCHAR (255)  NULL,
    [SWIFT_BIC]                          VARCHAR (255)  NULL,
    [IBAN]                               VARCHAR (255)  NULL,
    [FEI_SSN]                            VARCHAR (255)  NULL,
    [OP_FEI_SSN]                         VARCHAR (255)  NULL,
    [IsStandAloneCompany]                TINYINT        NOT NULL,
    [CorporateRecipientID]               BIGINT         NULL,
    [IsRemittanceUser]                   TINYINT        NOT NULL,
    [PreProcessorName]                   VARCHAR (250)  NULL,
    [CompressRecipientCity]              VARCHAR (50)   NULL,
    [CompressRecipientState]             VARCHAR (50)   NULL,
    [CompressRecipientName]              VARCHAR (50)   NULL,
    [CompressRecipientAddress]           VARCHAR (100)  NULL,
    [CompressRecipientAddress1]          VARCHAR (100)  NULL,
    [NewCompressRecipientNameandAddress] VARCHAR (1000) NULL
);

